"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Definition of channel properties for hw devices
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ChannelPropertyDictionary(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ChannelPropertyMappingEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___ChannelPropertyEntry: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___ChannelPropertyEntry | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CHANNEL_PROPERTY_MAPPING_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def channel_property_mapping(self) -> _containers.MessageMap[_builtins.str, Global___ChannelPropertyEntry]: ...
    def __init__(
        self,
        *,
        channel_property_mapping: _abc.Mapping[_builtins.str, Global___ChannelPropertyEntry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_property_mapping", b"channel_property_mapping"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChannelPropertyDictionary: _TypeAlias = ChannelPropertyDictionary  # noqa: Y015

@_typing.final
class ChannelPropertyEntry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AWG_FIELD_NUMBER: _builtins.int
    RO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def awg(self) -> Global___AWGProperties: ...
    @_builtins.property
    def ro(self) -> Global___ReadoutProperties: ...
    def __init__(
        self,
        *,
        awg: Global___AWGProperties | None = ...,
        ro: Global___ReadoutProperties | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["awg", b"awg", "ro", b"ro", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["awg", b"awg", "ro", b"ro", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["awg", "ro"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___ChannelPropertyEntry: _TypeAlias = ChannelPropertyEntry  # noqa: Y015

@_typing.final
class ChannelProperties(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAMPLING_RATE_FIELD_NUMBER: _builtins.int
    INSTRUCTION_DURATION_GRANULARITY_FIELD_NUMBER: _builtins.int
    INSTRUCTION_DURATION_MIN_FIELD_NUMBER: _builtins.int
    COMPATIBLE_INSTRUCTIONS_FIELD_NUMBER: _builtins.int
    INSTRUCTION_DURATION_GRANULARITY_SAMPLES_FIELD_NUMBER: _builtins.int
    INSTRUCTION_DURATION_MIN_SAMPLES_FIELD_NUMBER: _builtins.int
    sampling_rate: _builtins.float
    """sample rate of the instrument responsible for the channel (in Hz)"""
    instruction_duration_granularity: _builtins.float
    """Unused"""
    instruction_duration_min: _builtins.float
    """Unused"""
    instruction_duration_granularity_samples: _builtins.int
    """all instruction durations on this channel must be multiples of this granularity (in samples)"""
    instruction_duration_min_samples: _builtins.int
    """all instruction durations on this channel must at least this long (in samples)"""
    @_builtins.property
    def compatible_instructions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """instruction types that are allowed on this channel"""

    def __init__(
        self,
        *,
        sampling_rate: _builtins.float = ...,
        instruction_duration_granularity: _builtins.float = ...,
        instruction_duration_min: _builtins.float = ...,
        compatible_instructions: _abc.Iterable[_builtins.str] | None = ...,
        instruction_duration_granularity_samples: _builtins.int = ...,
        instruction_duration_min_samples: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compatible_instructions", b"compatible_instructions", "instruction_duration_granularity", b"instruction_duration_granularity", "instruction_duration_granularity_samples", b"instruction_duration_granularity_samples", "instruction_duration_min", b"instruction_duration_min", "instruction_duration_min_samples", b"instruction_duration_min_samples", "sampling_rate", b"sampling_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChannelProperties: _TypeAlias = ChannelProperties  # noqa: Y015

@_typing.final
class AWGProperties(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_PROPERTIES_FIELD_NUMBER: _builtins.int
    FAST_FEEDBACK_SOURCES_FIELD_NUMBER: _builtins.int
    LOCAL_OSCILLATOR_FIELD_NUMBER: _builtins.int
    MIXER_CORRECTION_FIELD_NUMBER: _builtins.int
    local_oscillator: _builtins.bool
    """Whether this AWG contains a local oscillator or not."""
    mixer_correction: _builtins.bool
    """ Whether this AWG has mixer correction or not."""
    @_builtins.property
    def channel_properties(self) -> Global___ChannelProperties: ...
    @_builtins.property
    def fast_feedback_sources(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Defines compatible fast feedback sources"""

    def __init__(
        self,
        *,
        channel_properties: Global___ChannelProperties | None = ...,
        fast_feedback_sources: _abc.Iterable[_builtins.str] | None = ...,
        local_oscillator: _builtins.bool = ...,
        mixer_correction: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel_properties", b"channel_properties"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_properties", b"channel_properties", "fast_feedback_sources", b"fast_feedback_sources", "local_oscillator", b"local_oscillator", "mixer_correction", b"mixer_correction"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AWGProperties: _TypeAlias = AWGProperties  # noqa: Y015

@_typing.final
class ReadoutProperties(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_PROPERTIES_FIELD_NUMBER: _builtins.int
    INTEGRATION_START_DEAD_TIME_FIELD_NUMBER: _builtins.int
    INTEGRATION_STOP_DEAD_TIME_FIELD_NUMBER: _builtins.int
    INTEGRATION_START_DEAD_TIME_SAMPLES_FIELD_NUMBER: _builtins.int
    INTEGRATION_STOP_DEAD_TIME_SAMPLES_FIELD_NUMBER: _builtins.int
    integration_start_dead_time: _builtins.float
    """Unused."""
    integration_stop_dead_time: _builtins.float
    """Unused."""
    integration_start_dead_time_samples: _builtins.int
    """Dead time samples before integration"""
    integration_stop_dead_time_samples: _builtins.int
    """Dead time samples after integration."""
    @_builtins.property
    def channel_properties(self) -> Global___ChannelProperties: ...
    def __init__(
        self,
        *,
        channel_properties: Global___ChannelProperties | None = ...,
        integration_start_dead_time: _builtins.float = ...,
        integration_stop_dead_time: _builtins.float = ...,
        integration_start_dead_time_samples: _builtins.int = ...,
        integration_stop_dead_time_samples: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel_properties", b"channel_properties"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_properties", b"channel_properties", "integration_start_dead_time", b"integration_start_dead_time", "integration_start_dead_time_samples", b"integration_start_dead_time_samples", "integration_stop_dead_time", b"integration_stop_dead_time", "integration_stop_dead_time_samples", b"integration_stop_dead_time_samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadoutProperties: _TypeAlias = ReadoutProperties  # noqa: Y015
