"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Protobuf message definitions for shared data types.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Complex128(_message.Message):
    """
    A complex number.
    """

    DESCRIPTOR: _descriptor.Descriptor

    REAL_FIELD_NUMBER: _builtins.int
    IMAG_FIELD_NUMBER: _builtins.int
    real: _builtins.float
    imag: _builtins.float
    def __init__(
        self,
        *,
        real: _builtins.float = ...,
        imag: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["imag", b"imag", "real", b"real"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Complex128: _TypeAlias = Complex128  # noqa: Y015

@_typing.final
class Int64Sequence(_message.Message):
    """
    Sequence of integers.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Int64Sequence: _TypeAlias = Int64Sequence  # noqa: Y015

@_typing.final
class Float64Sequence(_message.Message):
    """
    Sequence of doubles.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Float64Sequence: _TypeAlias = Float64Sequence  # noqa: Y015

@_typing.final
class BoolSequence(_message.Message):
    """
    Sequence of booleans.
    Protobuf uses ints to encode booleans, but keeps track of the type.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[_builtins.bool] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BoolSequence: _TypeAlias = BoolSequence  # noqa: Y015

@_typing.final
class Complex128Sequence(_message.Message):
    """
    Sequence of complex numbers.
    """

    DESCRIPTOR: _descriptor.Descriptor

    REAL_FIELD_NUMBER: _builtins.int
    IMAG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def real(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def imag(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        real: _abc.Iterable[_builtins.float] | None = ...,
        imag: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["imag", b"imag", "real", b"real"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Complex128Sequence: _TypeAlias = Complex128Sequence  # noqa: Y015

@_typing.final
class StringSequence(_message.Message):
    """
    Sequence of strings.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StringSequence: _TypeAlias = StringSequence  # noqa: Y015

@_typing.final
class Array(_message.Message):
    """
    Generic n-dimensional array, the dimensions of which are
    enumerated in 'shape' (think of "some_numpy_array.shape"),
    and the values themselves are enumerated in "items"  in big-endian order;
    the first dimension is the slowest to change
    (think of "numpy.nditer(some_numpy_array, order='C')").
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHAPE_FIELD_NUMBER: _builtins.int
    STRING_ARRAY_FIELD_NUMBER: _builtins.int
    BOOL_ARRAY_FIELD_NUMBER: _builtins.int
    INT64_ARRAY_FIELD_NUMBER: _builtins.int
    FLOAT64_ARRAY_FIELD_NUMBER: _builtins.int
    COMPLEX128_ARRAY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def string_array(self) -> Global___StringSequence: ...
    @_builtins.property
    def bool_array(self) -> Global___BoolSequence: ...
    @_builtins.property
    def int64_array(self) -> Global___Int64Sequence: ...
    @_builtins.property
    def float64_array(self) -> Global___Float64Sequence: ...
    @_builtins.property
    def complex128_array(self) -> Global___Complex128Sequence: ...
    def __init__(
        self,
        *,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        string_array: Global___StringSequence | None = ...,
        bool_array: Global___BoolSequence | None = ...,
        int64_array: Global___Int64Sequence | None = ...,
        float64_array: Global___Float64Sequence | None = ...,
        complex128_array: Global___Complex128Sequence | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_array", b"bool_array", "complex128_array", b"complex128_array", "float64_array", b"float64_array", "int64_array", b"int64_array", "kind", b"kind", "string_array", b"string_array"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_array", b"bool_array", "complex128_array", b"complex128_array", "float64_array", b"float64_array", "int64_array", b"int64_array", "kind", b"kind", "shape", b"shape", "string_array", b"string_array"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["string_array", "bool_array", "int64_array", "float64_array", "complex128_array"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___Array: _TypeAlias = Array  # noqa: Y015

@_typing.final
class Arrays(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARRAYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def arrays(self) -> _containers.RepeatedCompositeFieldContainer[Global___Array]: ...
    def __init__(
        self,
        *,
        arrays: _abc.Iterable[Global___Array] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arrays", b"arrays"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Arrays: _TypeAlias = Arrays  # noqa: Y015

@_typing.final
class Sequence(_message.Message):
    """
    Generic sequence.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STRING_ARRAY_FIELD_NUMBER: _builtins.int
    BOOL_ARRAY_FIELD_NUMBER: _builtins.int
    INT64_ARRAY_FIELD_NUMBER: _builtins.int
    FLOAT64_ARRAY_FIELD_NUMBER: _builtins.int
    COMPLEX128_ARRAY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def string_array(self) -> Global___StringSequence: ...
    @_builtins.property
    def bool_array(self) -> Global___BoolSequence: ...
    @_builtins.property
    def int64_array(self) -> Global___Int64Sequence: ...
    @_builtins.property
    def float64_array(self) -> Global___Float64Sequence: ...
    @_builtins.property
    def complex128_array(self) -> Global___Complex128Sequence: ...
    def __init__(
        self,
        *,
        string_array: Global___StringSequence | None = ...,
        bool_array: Global___BoolSequence | None = ...,
        int64_array: Global___Int64Sequence | None = ...,
        float64_array: Global___Float64Sequence | None = ...,
        complex128_array: Global___Complex128Sequence | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_array", b"bool_array", "complex128_array", b"complex128_array", "float64_array", b"float64_array", "int64_array", b"int64_array", "kind", b"kind", "string_array", b"string_array"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_array", b"bool_array", "complex128_array", b"complex128_array", "float64_array", b"float64_array", "int64_array", b"int64_array", "kind", b"kind", "string_array", b"string_array"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["string_array", "bool_array", "int64_array", "float64_array", "complex128_array"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___Sequence: _TypeAlias = Sequence  # noqa: Y015

@_typing.final
class Datum(_message.Message):
    """
    A single piece of data with flexible datatype. To be used in, for example, in settings.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STRING_VALUE_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    SINT64_VALUE_FIELD_NUMBER: _builtins.int
    FLOAT64_VALUE_FIELD_NUMBER: _builtins.int
    COMPLEX128_VALUE_FIELD_NUMBER: _builtins.int
    ARRAY_FIELD_NUMBER: _builtins.int
    SEQUENCE_FIELD_NUMBER: _builtins.int
    NULL_VALUE_FIELD_NUMBER: _builtins.int
    string_value: _builtins.str
    bool_value: _builtins.bool
    sint64_value: _builtins.int
    float64_value: _builtins.float
    null_value: _struct_pb2.NullValue.ValueType
    @_builtins.property
    def complex128_value(self) -> Global___Complex128: ...
    @_builtins.property
    def array(self) -> Global___Array: ...
    @_builtins.property
    def sequence(self) -> Global___Sequence: ...
    def __init__(
        self,
        *,
        string_value: _builtins.str = ...,
        bool_value: _builtins.bool = ...,
        sint64_value: _builtins.int = ...,
        float64_value: _builtins.float = ...,
        complex128_value: Global___Complex128 | None = ...,
        array: Global___Array | None = ...,
        sequence: Global___Sequence | None = ...,
        null_value: _struct_pb2.NullValue.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "bool_value", b"bool_value", "complex128_value", b"complex128_value", "float64_value", b"float64_value", "kind", b"kind", "null_value", b"null_value", "sequence", b"sequence", "sint64_value", b"sint64_value", "string_value", b"string_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "bool_value", b"bool_value", "complex128_value", b"complex128_value", "float64_value", b"float64_value", "kind", b"kind", "null_value", b"null_value", "sequence", b"sequence", "sint64_value", b"sint64_value", "string_value", b"string_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["string_value", "bool_value", "sint64_value", "float64_value", "complex128_value", "array", "sequence", "null_value"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___Datum: _TypeAlias = Datum  # noqa: Y015
