"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Observation value and uncertainty declarations.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from iqm.data_definitions.common.v1 import data_types_pb2 as _data_types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Int64Array(_message.Message):
    """
    Represents an integer array, the dimensions of which are
    enumerated in 'shape' (think of "some_numpy_array.shape"),
    and the integers themselves are enumerated in "items"
    (think of "numpy.nditer(some_numpy_array, order='C')").
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHAPE_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        items: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Int64Array: _TypeAlias = Int64Array  # noqa: Y015

@_typing.final
class Float64Array(_message.Message):
    """
    Represents a float array, the dimensions of which are
    enumerated in 'shape' (think of "some_numpy_array.shape"),
    and the integers themselves are enumerated in "items"
    (think of "numpy.nditer(some_numpy_array, order='C')").
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHAPE_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        items: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Float64Array: _TypeAlias = Float64Array  # noqa: Y015

@_typing.final
class Complex128Array(_message.Message):
    """
    Represents a complex array, the dimensions of which are
    enumerated in 'shape' (think of "some_numpy_array.shape"),
    and the integers themselves are enumerated in "items"
    (think of "numpy.nditer(some_numpy_array, order='C')").
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHAPE_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[_data_types_pb2.Complex128]: ...
    def __init__(
        self,
        *,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        items: _abc.Iterable[_data_types_pb2.Complex128] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Complex128Array: _TypeAlias = Complex128Array  # noqa: Y015

@_typing.final
class ObservationValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STR_VALUE_FIELD_NUMBER: _builtins.int
    INT64_VALUE_FIELD_NUMBER: _builtins.int
    FLOAT64_VALUE_FIELD_NUMBER: _builtins.int
    COMPLEX128_VALUE_FIELD_NUMBER: _builtins.int
    INT64_ARRAY_FIELD_NUMBER: _builtins.int
    FLOAT64_ARRAY_FIELD_NUMBER: _builtins.int
    COMPLEX128_ARRAY_FIELD_NUMBER: _builtins.int
    LEGACY_VALUE_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    ARRAY_FIELD_NUMBER: _builtins.int
    str_value: _builtins.str
    int64_value: _builtins.int
    float64_value: _builtins.float
    legacy_value: _builtins.bytes
    bool_value: _builtins.bool
    @_builtins.property
    def complex128_value(self) -> _data_types_pb2.Complex128: ...
    @_builtins.property
    def int64_array(self) -> Global___Int64Array: ...
    @_builtins.property
    def float64_array(self) -> Global___Float64Array: ...
    @_builtins.property
    def complex128_array(self) -> Global___Complex128Array: ...
    @_builtins.property
    def array(self) -> _data_types_pb2.Array: ...
    def __init__(
        self,
        *,
        str_value: _builtins.str = ...,
        int64_value: _builtins.int = ...,
        float64_value: _builtins.float = ...,
        complex128_value: _data_types_pb2.Complex128 | None = ...,
        int64_array: Global___Int64Array | None = ...,
        float64_array: Global___Float64Array | None = ...,
        complex128_array: Global___Complex128Array | None = ...,
        legacy_value: _builtins.bytes = ...,
        bool_value: _builtins.bool = ...,
        array: _data_types_pb2.Array | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "bool_value", b"bool_value", "complex128_array", b"complex128_array", "complex128_value", b"complex128_value", "float64_array", b"float64_array", "float64_value", b"float64_value", "int64_array", b"int64_array", "int64_value", b"int64_value", "legacy_value", b"legacy_value", "str_value", b"str_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "bool_value", b"bool_value", "complex128_array", b"complex128_array", "complex128_value", b"complex128_value", "float64_array", b"float64_array", "float64_value", b"float64_value", "int64_array", b"int64_array", "int64_value", b"int64_value", "legacy_value", b"legacy_value", "str_value", b"str_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["str_value", "int64_value", "float64_value", "complex128_value", "int64_array", "float64_array", "complex128_array", "legacy_value", "bool_value", "array"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___ObservationValue: _TypeAlias = ObservationValue  # noqa: Y015

@_typing.final
class ObservationUncertainty(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INT64_VALUE_FIELD_NUMBER: _builtins.int
    FLOAT64_VALUE_FIELD_NUMBER: _builtins.int
    COMPLEX128_VALUE_FIELD_NUMBER: _builtins.int
    INT64_ARRAY_FIELD_NUMBER: _builtins.int
    FLOAT64_ARRAY_FIELD_NUMBER: _builtins.int
    COMPLEX128_ARRAY_FIELD_NUMBER: _builtins.int
    LEGACY_VALUE_FIELD_NUMBER: _builtins.int
    int64_value: _builtins.int
    float64_value: _builtins.float
    legacy_value: _builtins.bytes
    @_builtins.property
    def complex128_value(self) -> _data_types_pb2.Complex128: ...
    @_builtins.property
    def int64_array(self) -> Global___Int64Array: ...
    @_builtins.property
    def float64_array(self) -> Global___Float64Array: ...
    @_builtins.property
    def complex128_array(self) -> Global___Complex128Array: ...
    def __init__(
        self,
        *,
        int64_value: _builtins.int = ...,
        float64_value: _builtins.float = ...,
        complex128_value: _data_types_pb2.Complex128 | None = ...,
        int64_array: Global___Int64Array | None = ...,
        float64_array: Global___Float64Array | None = ...,
        complex128_array: Global___Complex128Array | None = ...,
        legacy_value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["complex128_array", b"complex128_array", "complex128_value", b"complex128_value", "float64_array", b"float64_array", "float64_value", b"float64_value", "int64_array", b"int64_array", "int64_value", b"int64_value", "legacy_value", b"legacy_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["complex128_array", b"complex128_array", "complex128_value", b"complex128_value", "float64_array", b"float64_array", "float64_value", b"float64_value", "int64_array", b"int64_array", "int64_value", b"int64_value", "legacy_value", b"legacy_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["int64_value", "float64_value", "complex128_value", "int64_array", "float64_array", "complex128_array", "legacy_value"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___ObservationUncertainty: _TypeAlias = ObservationUncertainty  # noqa: Y015
