"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Protobuf message definitions for generic parameters.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Parameter(_message.Message):
    """Station Control parameter"""

    DESCRIPTOR: _descriptor.Descriptor

    class _CollectionType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CollectionTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Parameter._CollectionType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        COLLECTION_TYPE_UNSPECIFIED: Parameter._CollectionType.ValueType  # 0
        COLLECTION_TYPE_SCALAR: Parameter._CollectionType.ValueType  # 1
        COLLECTION_TYPE_SEQUENCE: Parameter._CollectionType.ValueType  # 2
        COLLECTION_TYPE_ARRAY: Parameter._CollectionType.ValueType  # 3

    class CollectionType(_CollectionType, metaclass=_CollectionTypeEnumTypeWrapper):
        """Collection type"""

    COLLECTION_TYPE_UNSPECIFIED: Parameter.CollectionType.ValueType  # 0
    COLLECTION_TYPE_SCALAR: Parameter.CollectionType.ValueType  # 1
    COLLECTION_TYPE_SEQUENCE: Parameter.CollectionType.ValueType  # 2
    COLLECTION_TYPE_ARRAY: Parameter.CollectionType.ValueType  # 3

    class _DataType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DataTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Parameter._DataType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DATA_TYPE_UNSPECIFIED: Parameter._DataType.ValueType  # 0
        DATA_TYPE_STRING: Parameter._DataType.ValueType  # 1
        DATA_TYPE_BOOL: Parameter._DataType.ValueType  # 2
        DATA_TYPE_INT64: Parameter._DataType.ValueType  # 3
        DATA_TYPE_FLOAT64: Parameter._DataType.ValueType  # 4
        DATA_TYPE_COMPLEX128: Parameter._DataType.ValueType  # 5

    class DataType(_DataType, metaclass=_DataTypeEnumTypeWrapper):
        """Collection type"""

    DATA_TYPE_UNSPECIFIED: Parameter.DataType.ValueType  # 0
    DATA_TYPE_STRING: Parameter.DataType.ValueType  # 1
    DATA_TYPE_BOOL: Parameter.DataType.ValueType  # 2
    DATA_TYPE_INT64: Parameter.DataType.ValueType  # 3
    DATA_TYPE_FLOAT64: Parameter.DataType.ValueType  # 4
    DATA_TYPE_COMPLEX128: Parameter.DataType.ValueType  # 5

    NAME_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    UNIT_FIELD_NUMBER: _builtins.int
    COLLECTION_TYPE_FIELD_NUMBER: _builtins.int
    DATA_TYPE_FIELD_NUMBER: _builtins.int
    ELEMENT_INDICES_FIELD_NUMBER: _builtins.int
    PARENT_NAME_FIELD_NUMBER: _builtins.int
    PARENT_LABEL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """parameter name"""
    label: _builtins.str
    """human-readable label"""
    unit: _builtins.str
    """SI unit"""
    collection_type: Global___Parameter.CollectionType.ValueType
    data_type: Global___Parameter.DataType.ValueType
    parent_name: _builtins.str
    parent_label: _builtins.str
    @_builtins.property
    def element_indices(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        label: _builtins.str = ...,
        unit: _builtins.str = ...,
        collection_type: Global___Parameter.CollectionType.ValueType = ...,
        data_type: Global___Parameter.DataType.ValueType = ...,
        element_indices: _abc.Iterable[_builtins.int] | None = ...,
        parent_name: _builtins.str = ...,
        parent_label: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["collection_type", b"collection_type", "data_type", b"data_type", "element_indices", b"element_indices", "label", b"label", "name", b"name", "parent_label", b"parent_label", "parent_name", b"parent_name", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Parameter: _TypeAlias = Parameter  # noqa: Y015
