"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019-2025 IQM

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Playlist(_message.Message):
    """Sequence of instruction schedules to execute."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ChannelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___ChannelDescription: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___ChannelDescription | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CHANNELS_FIELD_NUMBER: _builtins.int
    SCHEDULES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def channels(self) -> _containers.MessageMap[_builtins.str, Global___ChannelDescription]: ...
    @_builtins.property
    def schedules(self) -> _containers.RepeatedCompositeFieldContainer[Global___Schedule]: ...
    def __init__(
        self,
        *,
        channels: _abc.Mapping[_builtins.str, Global___ChannelDescription] | None = ...,
        schedules: _abc.Iterable[Global___Schedule] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "schedules", b"schedules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Playlist: _TypeAlias = Playlist  # noqa: Y015

@_typing.final
class Schedule(_message.Message):
    """Synchronous instruction segment to be executed on several control channels in parallel."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Channel(_message.Message):
        """list of ChannelDescription.instruction_table references for a single control channel"""

        DESCRIPTOR: _descriptor.Descriptor

        INSTRUCTION_REFS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def instruction_refs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            instruction_refs: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["instruction_refs", b"instruction_refs"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ChannelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Schedule.Channel: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Schedule.Channel | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CHANNELS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def channels(self) -> _containers.MessageMap[_builtins.str, Global___Schedule.Channel]:
        """mapping from channel names to their contents"""

    def __init__(
        self,
        *,
        channels: _abc.Mapping[_builtins.str, Global___Schedule.Channel] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Schedule: _TypeAlias = Schedule  # noqa: Y015

@_typing.final
class IQChannelConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    sample_rate: _builtins.float
    def __init__(
        self,
        *,
        sample_rate: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sample_rate", b"sample_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IQChannelConfig: _TypeAlias = IQChannelConfig  # noqa: Y015

@_typing.final
class RealChannelConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    sample_rate: _builtins.float
    def __init__(
        self,
        *,
        sample_rate: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sample_rate", b"sample_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RealChannelConfig: _TypeAlias = RealChannelConfig  # noqa: Y015

@_typing.final
class ReadoutChannelConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    sample_rate: _builtins.float
    def __init__(
        self,
        *,
        sample_rate: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sample_rate", b"sample_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadoutChannelConfig: _TypeAlias = ReadoutChannelConfig  # noqa: Y015

@_typing.final
class ChannelConfiguration(_message.Message):
    """Requested configuration for a control channel."""

    DESCRIPTOR: _descriptor.Descriptor

    IQ_CHANNEL_FIELD_NUMBER: _builtins.int
    REAL_CHANNEL_FIELD_NUMBER: _builtins.int
    RO_CHANNEL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def iq_channel(self) -> Global___IQChannelConfig: ...
    @_builtins.property
    def real_channel(self) -> Global___RealChannelConfig: ...
    @_builtins.property
    def ro_channel(self) -> Global___ReadoutChannelConfig: ...
    def __init__(
        self,
        *,
        iq_channel: Global___IQChannelConfig | None = ...,
        real_channel: Global___RealChannelConfig | None = ...,
        ro_channel: Global___ReadoutChannelConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["extended", b"extended", "iq_channel", b"iq_channel", "real_channel", b"real_channel", "ro_channel", b"ro_channel"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extended", b"extended", "iq_channel", b"iq_channel", "real_channel", b"real_channel", "ro_channel", b"ro_channel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_extended: _TypeAlias = _typing.Literal["iq_channel", "real_channel", "ro_channel"]  # noqa: Y015
    _WhichOneofArgType_extended: _TypeAlias = _typing.Literal["extended", b"extended"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_extended) -> _WhichOneofReturnType_extended | None: ...

Global___ChannelConfiguration: _TypeAlias = ChannelConfiguration  # noqa: Y015

@_typing.final
class ChannelDescription(_message.Message):
    """Describes a single control channel in a Playlist."""

    DESCRIPTOR: _descriptor.Descriptor

    CONTROLLER_NAME_FIELD_NUMBER: _builtins.int
    CHANNEL_CONFIG_FIELD_NUMBER: _builtins.int
    INSTRUCTION_TABLE_FIELD_NUMBER: _builtins.int
    WAVEFORM_TABLE_FIELD_NUMBER: _builtins.int
    ACQUISITION_TABLE_FIELD_NUMBER: _builtins.int
    controller_name: _builtins.str
    """name of the controller handling the control channel"""
    @_builtins.property
    def channel_config(self) -> Global___ChannelConfiguration:
        """requested configuration for the channel"""

    @_builtins.property
    def instruction_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Instruction]:
        """instruction and waveform lookup tables for the channel (Schedule refers to these)"""

    @_builtins.property
    def waveform_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___Waveform]: ...
    @_builtins.property
    def acquisition_table(self) -> _containers.RepeatedCompositeFieldContainer[Global___AcquisitionMethod]:
        """Table of acquisition configs. Only relevant for readout channels.
        Restrictions that may apply:
        - At most one time trace operation allowed.
        - Mixing of time traces and state discrimination not allowed.
        """

    def __init__(
        self,
        *,
        controller_name: _builtins.str = ...,
        channel_config: Global___ChannelConfiguration | None = ...,
        instruction_table: _abc.Iterable[Global___Instruction] | None = ...,
        waveform_table: _abc.Iterable[Global___Waveform] | None = ...,
        acquisition_table: _abc.Iterable[Global___AcquisitionMethod] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel_config", b"channel_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acquisition_table", b"acquisition_table", "channel_config", b"channel_config", "controller_name", b"controller_name", "instruction_table", b"instruction_table", "waveform_table", b"waveform_table"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChannelDescription: _TypeAlias = ChannelDescription  # noqa: Y015

@_typing.final
class Instruction(_message.Message):
    """Instructions are things instruments can do, and are executed back to back as referenced in each Schedule.Channel.
    Not all instruction types are supported by all channels.
    If a wrong instruction type is used, the Playlist is rejected.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DURATION_SAMPLES_FIELD_NUMBER: _builtins.int
    MULTIPLEXED_REAL_PULSE_FIELD_NUMBER: _builtins.int
    MULTIPLEXED_IQ_PULSE_FIELD_NUMBER: _builtins.int
    WAIT_FIELD_NUMBER: _builtins.int
    REAL_PULSE_FIELD_NUMBER: _builtins.int
    IQ_PULSE_FIELD_NUMBER: _builtins.int
    VIRTUAL_RZ_FIELD_NUMBER: _builtins.int
    CONDITIONAL_INSTRUCTION_FIELD_NUMBER: _builtins.int
    READOUT_TRIGGER_FIELD_NUMBER: _builtins.int
    duration_samples: _builtins.int
    @_builtins.property
    def multiplexed_real_pulse(self) -> Global___MultiplexedRealPulse: ...
    @_builtins.property
    def multiplexed_iq_pulse(self) -> Global___MultiplexedIQPulse: ...
    @_builtins.property
    def wait(self) -> Global___Wait: ...
    @_builtins.property
    def real_pulse(self) -> Global___RealPulse: ...
    @_builtins.property
    def iq_pulse(self) -> Global___IQPulse: ...
    @_builtins.property
    def virtual_rz(self) -> Global___VirtualRZ: ...
    @_builtins.property
    def conditional_instruction(self) -> Global___ConditionalInstruction: ...
    @_builtins.property
    def readout_trigger(self) -> Global___ReadoutTrigger: ...
    def __init__(
        self,
        *,
        duration_samples: _builtins.int = ...,
        multiplexed_real_pulse: Global___MultiplexedRealPulse | None = ...,
        multiplexed_iq_pulse: Global___MultiplexedIQPulse | None = ...,
        wait: Global___Wait | None = ...,
        real_pulse: Global___RealPulse | None = ...,
        iq_pulse: Global___IQPulse | None = ...,
        virtual_rz: Global___VirtualRZ | None = ...,
        conditional_instruction: Global___ConditionalInstruction | None = ...,
        readout_trigger: Global___ReadoutTrigger | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conditional_instruction", b"conditional_instruction", "iq_pulse", b"iq_pulse", "multiplexed_iq_pulse", b"multiplexed_iq_pulse", "multiplexed_real_pulse", b"multiplexed_real_pulse", "operation", b"operation", "readout_trigger", b"readout_trigger", "real_pulse", b"real_pulse", "virtual_rz", b"virtual_rz", "wait", b"wait"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conditional_instruction", b"conditional_instruction", "duration_samples", b"duration_samples", "iq_pulse", b"iq_pulse", "multiplexed_iq_pulse", b"multiplexed_iq_pulse", "multiplexed_real_pulse", b"multiplexed_real_pulse", "operation", b"operation", "readout_trigger", b"readout_trigger", "real_pulse", b"real_pulse", "virtual_rz", b"virtual_rz", "wait", b"wait"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_operation: _TypeAlias = _typing.Literal["multiplexed_real_pulse", "multiplexed_iq_pulse", "wait", "real_pulse", "iq_pulse", "virtual_rz", "conditional_instruction", "readout_trigger"]  # noqa: Y015
    _WhichOneofArgType_operation: _TypeAlias = _typing.Literal["operation", b"operation"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_operation) -> _WhichOneofReturnType_operation | None: ...

Global___Instruction: _TypeAlias = Instruction  # noqa: Y015

@_typing.final
class AcquisitionMethod(_message.Message):
    """Acquisition methods"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TimeTrace(_message.Message):
        """Capture the raw IQ signal without integration."""

        DESCRIPTOR: _descriptor.Descriptor

        DURATION_SAMPLES_FIELD_NUMBER: _builtins.int
        duration_samples: _builtins.int
        """How many samples to capture."""
        def __init__(
            self,
            *,
            duration_samples: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_samples", b"duration_samples"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ComplexIntegration(_message.Message):
        """Perform a weighted integration of the IQ raw signal, resulting a complex number."""

        DESCRIPTOR: _descriptor.Descriptor

        WEIGHTS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def weights(self) -> Global___IQPulse:
            """Complex IQ weight to use.
            The total integration window is the maximum length of all integration weights.
            A weights vector shorter than the window is padded with zeros.
            """

        def __init__(
            self,
            *,
            weights: Global___IQPulse | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["weights", b"weights"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["weights", b"weights"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ThresholdStateDiscrimination(_message.Message):
        """Perform a weighted integration of the IQ raw signal and compares the real part of the result against a
        threshold value, resulting in a boolean.
        """

        DESCRIPTOR: _descriptor.Descriptor

        WEIGHTS_FIELD_NUMBER: _builtins.int
        THRESHOLD_FIELD_NUMBER: _builtins.int
        FEEDBACK_SIGNAL_LABEL_FIELD_NUMBER: _builtins.int
        threshold: _builtins.float
        """Threshold value used in discrimination."""
        feedback_signal_label: _builtins.str
        """In fast feedback routing, the transmitted signals are associated with this label.
        ConditionalInstructions whose "condition" field has the string value of "feedback_signal_label"
        will receive the signal from this ThresholdStateDiscrimination.
        Empty string (default) means the signal is not routed anywhere.
        The same feedback_signal_label may not be used multiple times within the same ReadoutTrigger.
        The same feedback_signal_label can be used in different ReadoutTriggers and different segments.
        """
        @_builtins.property
        def weights(self) -> Global___IQPulse:
            """Same as in ComplexIntegration"""

        def __init__(
            self,
            *,
            weights: Global___IQPulse | None = ...,
            threshold: _builtins.float = ...,
            feedback_signal_label: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["weights", b"weights"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["feedback_signal_label", b"feedback_signal_label", "threshold", b"threshold", "weights", b"weights"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    LABEL_FIELD_NUMBER: _builtins.int
    DELAY_SAMPLES_FIELD_NUMBER: _builtins.int
    TIMETRACE_FIELD_NUMBER: _builtins.int
    INTEGRATION_FIELD_NUMBER: _builtins.int
    THRESHOLD_DISCRIMINATION_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    """Identifier for the returned data, like "QB1__readout.time_trace" """
    delay_samples: _builtins.int
    """How much the start of the acquisition should be delayed after the trigger, in samples."""
    @_builtins.property
    def timetrace(self) -> Global___AcquisitionMethod.TimeTrace: ...
    @_builtins.property
    def integration(self) -> Global___AcquisitionMethod.ComplexIntegration: ...
    @_builtins.property
    def threshold_discrimination(self) -> Global___AcquisitionMethod.ThresholdStateDiscrimination: ...
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        delay_samples: _builtins.int = ...,
        timetrace: Global___AcquisitionMethod.TimeTrace | None = ...,
        integration: Global___AcquisitionMethod.ComplexIntegration | None = ...,
        threshold_discrimination: Global___AcquisitionMethod.ThresholdStateDiscrimination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["acquisition_type", b"acquisition_type", "integration", b"integration", "threshold_discrimination", b"threshold_discrimination", "timetrace", b"timetrace"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acquisition_type", b"acquisition_type", "delay_samples", b"delay_samples", "integration", b"integration", "label", b"label", "threshold_discrimination", b"threshold_discrimination", "timetrace", b"timetrace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_acquisition_type: _TypeAlias = _typing.Literal["timetrace", "integration", "threshold_discrimination"]  # noqa: Y015
    _WhichOneofArgType_acquisition_type: _TypeAlias = _typing.Literal["acquisition_type", b"acquisition_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_acquisition_type) -> _WhichOneofReturnType_acquisition_type | None: ...

Global___AcquisitionMethod: _TypeAlias = AcquisitionMethod  # noqa: Y015

@_typing.final
class Wait(_message.Message):
    """Instruction for an instrument to wait. For AWGs, equivalent to playing zero-valued samples."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Wait: _TypeAlias = Wait  # noqa: Y015

@_typing.final
class VirtualRZ(_message.Message):
    """Instruction for a virtual z rotation."""

    DESCRIPTOR: _descriptor.Descriptor

    PHASE_INCREMENT_FIELD_NUMBER: _builtins.int
    phase_increment: _builtins.float
    def __init__(
        self,
        *,
        phase_increment: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["phase_increment", b"phase_increment"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VirtualRZ: _TypeAlias = VirtualRZ  # noqa: Y015

@_typing.final
class RealPulse(_message.Message):
    """Instruction for playing a real-valued pulse, to be used with real channels."""

    DESCRIPTOR: _descriptor.Descriptor

    WAVEFORM_REF_FIELD_NUMBER: _builtins.int
    SCALE_FIELD_NUMBER: _builtins.int
    waveform_ref: _builtins.int
    scale: _builtins.float
    def __init__(
        self,
        *,
        waveform_ref: _builtins.int = ...,
        scale: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["scale", b"scale", "waveform_ref", b"waveform_ref"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RealPulse: _TypeAlias = RealPulse  # noqa: Y015

@_typing.final
class IQPulse(_message.Message):
    """Instruction for playing an IQ pulse, to be used with IQ channels."""

    DESCRIPTOR: _descriptor.Descriptor

    WAVEFORM_I_REF_FIELD_NUMBER: _builtins.int
    WAVEFORM_Q_REF_FIELD_NUMBER: _builtins.int
    SCALE_I_FIELD_NUMBER: _builtins.int
    SCALE_Q_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    PHASE_MOD_FREQ_FIELD_NUMBER: _builtins.int
    PHASE_INCREMENT_FIELD_NUMBER: _builtins.int
    waveform_i_ref: _builtins.int
    waveform_q_ref: _builtins.int
    scale_i: _builtins.float
    """Pulse modifiers that can be implemented in hardware.
    Semantics: first scale the i and q waves, then apply phase offset and modulation (mixing i and q),
    then apply extra accumulated phase from VirtualRZs, if present.
    Frequency modulation `phase_mod_freq` is applied relative to the start of the pulse, on top of any IF modulation in hardware;
      sideband modulating with this parameter will not result in phase-coherent pulses at the new sideband frequency.
    """
    scale_q: _builtins.float
    phase: _builtins.float
    phase_mod_freq: _builtins.float
    phase_increment: _builtins.float
    """Relative phase increment to the phase in the carrier frequency of this pulse and all pulses that are played after it. Unit: rad."""
    def __init__(
        self,
        *,
        waveform_i_ref: _builtins.int = ...,
        waveform_q_ref: _builtins.int = ...,
        scale_i: _builtins.float = ...,
        scale_q: _builtins.float = ...,
        phase: _builtins.float = ...,
        phase_mod_freq: _builtins.float = ...,
        phase_increment: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["phase", b"phase", "phase_increment", b"phase_increment", "phase_mod_freq", b"phase_mod_freq", "scale_i", b"scale_i", "scale_q", b"scale_q", "waveform_i_ref", b"waveform_i_ref", "waveform_q_ref", b"waveform_q_ref"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IQPulse: _TypeAlias = IQPulse  # noqa: Y015

@_typing.final
class MultiplexedIQPulse(_message.Message):
    """Instruction to simultaneously play multiple IQ pulses.
    Each component pulse entry can be added with arbitrary delay from the beginning of this instruction.
    Where outside of the duration of the MultiplexedPulse, the pulse entries are truncated.
    Where overlapping, samples of multiple pulse entries are summed.
    Where the interval of a MultiplexedPulse does not overlap with any of its entry pulse, its samples will be 0.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Entry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OFFSET_SAMPLES_FIELD_NUMBER: _builtins.int
        INSTRUCTION_REF_FIELD_NUMBER: _builtins.int
        IQ_PULSE_FIELD_NUMBER: _builtins.int
        offset_samples: _builtins.int
        """no granularity constraints. negative values allowed (but beginning will be truncated)"""
        instruction_ref: _builtins.int
        @_builtins.property
        def iq_pulse(self) -> Global___IQPulse: ...
        def __init__(
            self,
            *,
            offset_samples: _builtins.int = ...,
            instruction_ref: _builtins.int = ...,
            iq_pulse: Global___IQPulse | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["instruction_ref", b"instruction_ref", "iq_pulse", b"iq_pulse", "pulse", b"pulse"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["instruction_ref", b"instruction_ref", "iq_pulse", b"iq_pulse", "offset_samples", b"offset_samples", "pulse", b"pulse"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_pulse: _TypeAlias = _typing.Literal["instruction_ref", "iq_pulse"]  # noqa: Y015
        _WhichOneofArgType_pulse: _TypeAlias = _typing.Literal["pulse", b"pulse"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_pulse) -> _WhichOneofReturnType_pulse | None: ...

    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___MultiplexedIQPulse.Entry]: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___MultiplexedIQPulse.Entry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MultiplexedIQPulse: _TypeAlias = MultiplexedIQPulse  # noqa: Y015

@_typing.final
class MultiplexedRealPulse(_message.Message):
    """Similar to MultiplexedIQPulse, but for real pulses."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Entry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OFFSET_SAMPLES_FIELD_NUMBER: _builtins.int
        INSTRUCTION_REF_FIELD_NUMBER: _builtins.int
        REAL_PULSE_FIELD_NUMBER: _builtins.int
        offset_samples: _builtins.int
        instruction_ref: _builtins.int
        @_builtins.property
        def real_pulse(self) -> Global___RealPulse: ...
        def __init__(
            self,
            *,
            offset_samples: _builtins.int = ...,
            instruction_ref: _builtins.int = ...,
            real_pulse: Global___RealPulse | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["instruction_ref", b"instruction_ref", "pulse", b"pulse", "real_pulse", b"real_pulse"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["instruction_ref", b"instruction_ref", "offset_samples", b"offset_samples", "pulse", b"pulse", "real_pulse", b"real_pulse"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_pulse: _TypeAlias = _typing.Literal["instruction_ref", "real_pulse"]  # noqa: Y015
        _WhichOneofArgType_pulse: _TypeAlias = _typing.Literal["pulse", b"pulse"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_pulse) -> _WhichOneofReturnType_pulse | None: ...

    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___MultiplexedRealPulse.Entry]: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___MultiplexedRealPulse.Entry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MultiplexedRealPulse: _TypeAlias = MultiplexedRealPulse  # noqa: Y015

@_typing.final
class ReadoutTrigger(_message.Message):
    """Instruction for playing a probe pulse and acquiring the associated readout results.
    Supported by ReadoutChannelConfig channels.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PROBE_PULSE_REF_FIELD_NUMBER: _builtins.int
    ACQUSITIONS_FIELD_NUMBER: _builtins.int
    probe_pulse_ref: _builtins.int
    """Index of the pulse instruction, from the instruction table of the channel description."""
    @_builtins.property
    def acqusitions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Indices into AcquisitionMethod table of the channel config."""

    def __init__(
        self,
        *,
        probe_pulse_ref: _builtins.int = ...,
        acqusitions: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acqusitions", b"acqusitions", "probe_pulse_ref", b"probe_pulse_ref"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadoutTrigger: _TypeAlias = ReadoutTrigger  # noqa: Y015

@_typing.final
class ConditionalInstruction(_message.Message):
    """Choice between two instructions based on a condition."""

    DESCRIPTOR: _descriptor.Descriptor

    CONDITION_FIELD_NUMBER: _builtins.int
    IF_TRUE_FIELD_NUMBER: _builtins.int
    IF_FALSE_FIELD_NUMBER: _builtins.int
    condition: _builtins.str
    if_true: _builtins.int
    """ChannelDescription.instruction_table references for the potential outcomes"""
    if_false: _builtins.int
    def __init__(
        self,
        *,
        condition: _builtins.str = ...,
        if_true: _builtins.int = ...,
        if_false: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["condition", b"condition", "if_false", b"if_false", "if_true", b"if_true"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConditionalInstruction: _TypeAlias = ConditionalInstruction  # noqa: Y015

@_typing.final
class Waveform(_message.Message):
    """Real-valued waveform to be stored in AWG waveform memory, can be referenced by various Instructions."""

    DESCRIPTOR: _descriptor.Descriptor

    N_SAMPLES_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    GAUSSIAN_FIELD_NUMBER: _builtins.int
    GAUSSIAN_DERIVATIVE_FIELD_NUMBER: _builtins.int
    CONSTANT_FIELD_NUMBER: _builtins.int
    GAUSSIAN_SMOOTHED_SQUARE_FIELD_NUMBER: _builtins.int
    TRUNCATED_GAUSSIAN_FIELD_NUMBER: _builtins.int
    TRUNCATED_GAUSSIAN_DERIVATIVE_FIELD_NUMBER: _builtins.int
    TRUNCATED_GAUSSIAN_SMOOTHED_SQUARE_FIELD_NUMBER: _builtins.int
    COSINE_RISE_FALL_FIELD_NUMBER: _builtins.int
    COSINE_RISE_FALL_DERIVATIVE_FIELD_NUMBER: _builtins.int
    MODULATED_COSINE_RISE_FALL_FIELD_NUMBER: _builtins.int
    SLEPIAN_FIELD_NUMBER: _builtins.int
    n_samples: _builtins.int
    @_builtins.property
    def samples(self) -> Global___Samples: ...
    @_builtins.property
    def gaussian(self) -> Global___Gaussian: ...
    @_builtins.property
    def gaussian_derivative(self) -> Global___GaussianDerivative: ...
    @_builtins.property
    def constant(self) -> Global___Constant: ...
    @_builtins.property
    def gaussian_smoothed_square(self) -> Global___GaussianSmoothedSquare: ...
    @_builtins.property
    def truncated_gaussian(self) -> Global___TruncatedGaussian: ...
    @_builtins.property
    def truncated_gaussian_derivative(self) -> Global___TruncatedGaussianDerivative: ...
    @_builtins.property
    def truncated_gaussian_smoothed_square(self) -> Global___TruncatedGaussianSmoothedSquare: ...
    @_builtins.property
    def cosine_rise_fall(self) -> Global___CosineRiseFall: ...
    @_builtins.property
    def cosine_rise_fall_derivative(self) -> Global___CosineRiseFallDerivative: ...
    @_builtins.property
    def modulated_cosine_rise_fall(self) -> Global___ModulatedCosineRiseFall: ...
    @_builtins.property
    def slepian(self) -> Global___Slepian: ...
    def __init__(
        self,
        *,
        n_samples: _builtins.int = ...,
        samples: Global___Samples | None = ...,
        gaussian: Global___Gaussian | None = ...,
        gaussian_derivative: Global___GaussianDerivative | None = ...,
        constant: Global___Constant | None = ...,
        gaussian_smoothed_square: Global___GaussianSmoothedSquare | None = ...,
        truncated_gaussian: Global___TruncatedGaussian | None = ...,
        truncated_gaussian_derivative: Global___TruncatedGaussianDerivative | None = ...,
        truncated_gaussian_smoothed_square: Global___TruncatedGaussianSmoothedSquare | None = ...,
        cosine_rise_fall: Global___CosineRiseFall | None = ...,
        cosine_rise_fall_derivative: Global___CosineRiseFallDerivative | None = ...,
        modulated_cosine_rise_fall: Global___ModulatedCosineRiseFall | None = ...,
        slepian: Global___Slepian | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["constant", b"constant", "cosine_rise_fall", b"cosine_rise_fall", "cosine_rise_fall_derivative", b"cosine_rise_fall_derivative", "gaussian", b"gaussian", "gaussian_derivative", b"gaussian_derivative", "gaussian_smoothed_square", b"gaussian_smoothed_square", "modulated_cosine_rise_fall", b"modulated_cosine_rise_fall", "samples", b"samples", "slepian", b"slepian", "truncated_gaussian", b"truncated_gaussian", "truncated_gaussian_derivative", b"truncated_gaussian_derivative", "truncated_gaussian_smoothed_square", b"truncated_gaussian_smoothed_square", "waveform_description", b"waveform_description"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["constant", b"constant", "cosine_rise_fall", b"cosine_rise_fall", "cosine_rise_fall_derivative", b"cosine_rise_fall_derivative", "gaussian", b"gaussian", "gaussian_derivative", b"gaussian_derivative", "gaussian_smoothed_square", b"gaussian_smoothed_square", "modulated_cosine_rise_fall", b"modulated_cosine_rise_fall", "n_samples", b"n_samples", "samples", b"samples", "slepian", b"slepian", "truncated_gaussian", b"truncated_gaussian", "truncated_gaussian_derivative", b"truncated_gaussian_derivative", "truncated_gaussian_smoothed_square", b"truncated_gaussian_smoothed_square", "waveform_description", b"waveform_description"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_waveform_description: _TypeAlias = _typing.Literal["samples", "gaussian", "gaussian_derivative", "constant", "gaussian_smoothed_square", "truncated_gaussian", "truncated_gaussian_derivative", "truncated_gaussian_smoothed_square", "cosine_rise_fall", "cosine_rise_fall_derivative", "modulated_cosine_rise_fall", "slepian"]  # noqa: Y015
    _WhichOneofArgType_waveform_description: _TypeAlias = _typing.Literal["waveform_description", b"waveform_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_waveform_description) -> _WhichOneofReturnType_waveform_description | None: ...

Global___Waveform: _TypeAlias = Waveform  # noqa: Y015

@_typing.final
class Samples(_message.Message):
    """Custom waveform consisting from a list of samples."""

    DESCRIPTOR: _descriptor.Descriptor

    SAMPLES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        samples: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["samples", b"samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Samples: _TypeAlias = Samples  # noqa: Y015

@_typing.final
class Gaussian(_message.Message):
    """Gaussian pulse."""

    DESCRIPTOR: _descriptor.Descriptor

    SIGMA_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    sigma: _builtins.float
    center_offset: _builtins.float
    def __init__(
        self,
        *,
        sigma: _builtins.float = ...,
        center_offset: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "sigma", b"sigma"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Gaussian: _TypeAlias = Gaussian  # noqa: Y015

@_typing.final
class GaussianDerivative(_message.Message):
    """Scaled derivative of a gaussian pulse."""

    DESCRIPTOR: _descriptor.Descriptor

    SIGMA_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    sigma: _builtins.float
    center_offset: _builtins.float
    def __init__(
        self,
        *,
        sigma: _builtins.float = ...,
        center_offset: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "sigma", b"sigma"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GaussianDerivative: _TypeAlias = GaussianDerivative  # noqa: Y015

@_typing.final
class Constant(_message.Message):
    """Constant-valued waveform."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Constant: _TypeAlias = Constant  # noqa: Y015

@_typing.final
class GaussianSmoothedSquare(_message.Message):
    """Convolution of a gaussian pulse and a square pulse."""

    DESCRIPTOR: _descriptor.Descriptor

    SQUARE_WIDTH_FIELD_NUMBER: _builtins.int
    GAUSSIAN_SIGMA_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    square_width: _builtins.float
    gaussian_sigma: _builtins.float
    center_offset: _builtins.float
    def __init__(
        self,
        *,
        square_width: _builtins.float = ...,
        gaussian_sigma: _builtins.float = ...,
        center_offset: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "gaussian_sigma", b"gaussian_sigma", "square_width", b"square_width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GaussianSmoothedSquare: _TypeAlias = GaussianSmoothedSquare  # noqa: Y015

@_typing.final
class TruncatedGaussian(_message.Message):
    """Gaussian pulse, where the decaying tails are removed by offsetting, truncating
    and then rescaling the pulse
    """

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    center_offset: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        center_offset: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "full_width", b"full_width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TruncatedGaussian: _TypeAlias = TruncatedGaussian  # noqa: Y015

@_typing.final
class TruncatedGaussianDerivative(_message.Message):
    """Derivative of a gaussian pulse, where the decaying tails are removed by offsetting,
    truncating and then rescaling the pulse
    """

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    center_offset: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        center_offset: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "full_width", b"full_width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TruncatedGaussianDerivative: _TypeAlias = TruncatedGaussianDerivative  # noqa: Y015

@_typing.final
class TruncatedGaussianSmoothedSquare(_message.Message):
    """Convolution of a square pulse and a gaussian pulse, offset and truncated so that it has finite support."""

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    RISE_TIME_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    center_offset: _builtins.float
    rise_time: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        center_offset: _builtins.float = ...,
        rise_time: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "full_width", b"full_width", "rise_time", b"rise_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TruncatedGaussianSmoothedSquare: _TypeAlias = TruncatedGaussianSmoothedSquare  # noqa: Y015

@_typing.final
class CosineRiseFall(_message.Message):
    """Waveform that has a sinusoidal rise and fall, and a constant part in between."""

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    RISE_TIME_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    center_offset: _builtins.float
    rise_time: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        center_offset: _builtins.float = ...,
        rise_time: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "full_width", b"full_width", "rise_time", b"rise_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CosineRiseFall: _TypeAlias = CosineRiseFall  # noqa: Y015

@_typing.final
class CosineRiseFallDerivative(_message.Message):
    """Derivative of a waveform that has a sinusoidal rise and fall, and a constant part in between."""

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    RISE_TIME_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    center_offset: _builtins.float
    rise_time: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        center_offset: _builtins.float = ...,
        rise_time: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "full_width", b"full_width", "rise_time", b"rise_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CosineRiseFallDerivative: _TypeAlias = CosineRiseFallDerivative  # noqa: Y015

@_typing.final
class ModulatedCosineRiseFall(_message.Message):
    """Modulated Cosine Rise Fall waveform."""

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    RISE_TIME_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    MODULATION_FREQUENCY_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    center_offset: _builtins.float
    rise_time: _builtins.float
    phase: _builtins.float
    modulation_frequency: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        center_offset: _builtins.float = ...,
        rise_time: _builtins.float = ...,
        phase: _builtins.float = ...,
        modulation_frequency: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "full_width", b"full_width", "modulation_frequency", b"modulation_frequency", "phase", b"phase", "rise_time", b"rise_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModulatedCosineRiseFall: _TypeAlias = ModulatedCosineRiseFall  # noqa: Y015

@_typing.final
class Slepian(_message.Message):
    """Slepian waveform, which minimizes non-adiabatic errors during a gate."""

    DESCRIPTOR: _descriptor.Descriptor

    FULL_WIDTH_FIELD_NUMBER: _builtins.int
    LAMBDA_1_FIELD_NUMBER: _builtins.int
    LAMBDA_2_FIELD_NUMBER: _builtins.int
    FREQUENCY_INITIAL_NORMALIZED_FIELD_NUMBER: _builtins.int
    FREQUENCY_TO_MINIMIZE_NORMALIZED_FIELD_NUMBER: _builtins.int
    COUPLING_STRENGTH_NORMALIZED_FIELD_NUMBER: _builtins.int
    CENTER_OFFSET_FIELD_NUMBER: _builtins.int
    SQUID_ASYMMETRY_FIELD_NUMBER: _builtins.int
    FLAT_WIDTH_FIELD_NUMBER: _builtins.int
    full_width: _builtins.float
    lambda_1: _builtins.float
    lambda_2: _builtins.float
    frequency_initial_normalized: _builtins.float
    frequency_to_minimize_normalized: _builtins.float
    coupling_strength_normalized: _builtins.float
    center_offset: _builtins.float
    squid_asymmetry: _builtins.float
    flat_width: _builtins.float
    def __init__(
        self,
        *,
        full_width: _builtins.float = ...,
        lambda_1: _builtins.float = ...,
        lambda_2: _builtins.float = ...,
        frequency_initial_normalized: _builtins.float = ...,
        frequency_to_minimize_normalized: _builtins.float = ...,
        coupling_strength_normalized: _builtins.float = ...,
        center_offset: _builtins.float = ...,
        squid_asymmetry: _builtins.float = ...,
        flat_width: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_offset", b"center_offset", "coupling_strength_normalized", b"coupling_strength_normalized", "flat_width", b"flat_width", "frequency_initial_normalized", b"frequency_initial_normalized", "frequency_to_minimize_normalized", b"frequency_to_minimize_normalized", "full_width", b"full_width", "lambda_1", b"lambda_1", "lambda_2", b"lambda_2", "squid_asymmetry", b"squid_asymmetry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Slepian: _TypeAlias = Slepian  # noqa: Y015
