"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Protobuf message definitions for transferring Station Control settings tree.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from iqm.data_definitions.common.v1 import data_types_pb2 as _data_types_pb2
from iqm.data_definitions.common.v1 import parameter_pb2 as _parameter_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SettingNode(_message.Message):
    """Node of a setting tree. Nodes in the tree consist of settings (leaves) or other nodes (branches)."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Setting(_message.Message):
        """Setting that combines a parameter and a value"""

        DESCRIPTOR: _descriptor.Descriptor

        PARAMETER_NAME_FIELD_NUMBER: _builtins.int
        PARAMETER_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        READ_ONLY_FIELD_NUMBER: _builtins.int
        parameter_name: _builtins.str
        """The string is to be used when request is sent to the server which already knows the aux data."""
        read_only: _builtins.bool
        """Whether the setting is read only. Default is False."""
        @_builtins.property
        def parameter(self) -> _parameter_pb2.Parameter:
            """Parameter is to be used when the auxiliary data, like unit and required datatype,
            must be communicated to a client.
            """

        @_builtins.property
        def value(self) -> _data_types_pb2.Datum:
            """The actual payload."""

        def __init__(
            self,
            *,
            parameter_name: _builtins.str = ...,
            parameter: _parameter_pb2.Parameter | None = ...,
            value: _data_types_pb2.Datum | None = ...,
            read_only: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_read_only", b"_read_only", "parameter", b"parameter", "parameter_desc", b"parameter_desc", "parameter_name", b"parameter_name", "read_only", b"read_only", "value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_read_only", b"_read_only", "parameter", b"parameter", "parameter_desc", b"parameter_desc", "parameter_name", b"parameter_name", "read_only", b"read_only", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__read_only: _TypeAlias = _typing.Literal["read_only"]  # noqa: Y015
        _WhichOneofArgType__read_only: _TypeAlias = _typing.Literal["_read_only", b"_read_only"]  # noqa: Y015
        _WhichOneofReturnType_parameter_desc: _TypeAlias = _typing.Literal["parameter_name", "parameter"]  # noqa: Y015
        _WhichOneofArgType_parameter_desc: _TypeAlias = _typing.Literal["parameter_desc", b"parameter_desc"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__read_only) -> _WhichOneofReturnType__read_only | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType_parameter_desc) -> _WhichOneofReturnType_parameter_desc | None: ...

    @_typing.final
    class SettingsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SettingNode.Setting: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___SettingNode.Setting | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SubnodesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SettingNode: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___SettingNode | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    SETTINGS_FIELD_NUMBER: _builtins.int
    SUBNODES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Name of the node. By convention, the name is a dot-separated string whose fragments are the keys leading from
    the root node to this node. For example, a nested node `root_node::sub_1::sub_2` should be named `"sub_1.sub_2"`
    which makes the name unique.
    """
    @_builtins.property
    def settings(self) -> _containers.MessageMap[_builtins.str, Global___SettingNode.Setting]:
        """Settings contained in this node."""

    @_builtins.property
    def subnodes(self) -> _containers.MessageMap[_builtins.str, Global___SettingNode]:
        """Subnodes contained in the node."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        settings: _abc.Mapping[_builtins.str, Global___SettingNode.Setting] | None = ...,
        subnodes: _abc.Mapping[_builtins.str, Global___SettingNode] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "settings", b"settings", "subnodes", b"subnodes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SettingNode: _TypeAlias = SettingNode  # noqa: Y015
