"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2019-2025 IQM

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _NullValue:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _NullValueEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_NullValue.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NULL_VALUE_UNSPECIFIED: _NullValue.ValueType  # 0
    """Null value."""

class NullValue(_NullValue, metaclass=_NullValueEnumTypeWrapper):
    """`NullValue` is a singleton enumeration to represent the null value for the
    `Value` type union.

    The JSON representation for `NullValue` is JSON `null`.
    """

NULL_VALUE_UNSPECIFIED: NullValue.ValueType  # 0
"""Null value."""
Global___NullValue: _TypeAlias = NullValue  # noqa: Y015

@_typing.final
class Struct(_message.Message):
    """`Struct` represents a structured data value, consisting of fields
    which map to dynamically typed values. In some languages, `Struct`
    might be supported by a native representation. For example, in
    scripting languages like JS a struct is represented as an
    object. The details of that representation are described together
    with the proto support for the language.

    The JSON representation for `Struct` is JSON object.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FieldsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Value: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    FIELDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def fields(self) -> _containers.MessageMap[_builtins.str, Global___Value]:
        """Unordered map of dynamically typed values."""

    def __init__(
        self,
        *,
        fields: _abc.Mapping[_builtins.str, Global___Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fields", b"fields"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Struct: _TypeAlias = Struct  # noqa: Y015

@_typing.final
class Value(_message.Message):
    """`Value` represents a dynamically typed value which can be either
    null, a double or an integer number, a string, a boolean, a recursive struct value, or a
    list of values. A producer of value is expected to set one of these
    variants. Absence of any variant indicates an error.

    The JSON representation for `Value` is JSON value.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NULL_VALUE_FIELD_NUMBER: _builtins.int
    NUMBER_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    STRUCT_VALUE_FIELD_NUMBER: _builtins.int
    LIST_VALUE_FIELD_NUMBER: _builtins.int
    INTEGER_VALUE_FIELD_NUMBER: _builtins.int
    null_value: Global___NullValue.ValueType
    """Represents a null value."""
    number_value: _builtins.float
    """Represents a double value."""
    string_value: _builtins.str
    """Represents a string value."""
    bool_value: _builtins.bool
    """Represents a boolean value."""
    integer_value: _builtins.int
    """Represents an integer value."""
    @_builtins.property
    def struct_value(self) -> Global___Struct:
        """Represents a structured value."""

    @_builtins.property
    def list_value(self) -> Global___ListValue:
        """Represents a repeated `Value`."""

    def __init__(
        self,
        *,
        null_value: Global___NullValue.ValueType = ...,
        number_value: _builtins.float = ...,
        string_value: _builtins.str = ...,
        bool_value: _builtins.bool = ...,
        struct_value: Global___Struct | None = ...,
        list_value: Global___ListValue | None = ...,
        integer_value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "integer_value", b"integer_value", "kind", b"kind", "list_value", b"list_value", "null_value", b"null_value", "number_value", b"number_value", "string_value", b"string_value", "struct_value", b"struct_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "integer_value", b"integer_value", "kind", b"kind", "list_value", b"list_value", "null_value", b"null_value", "number_value", b"number_value", "string_value", b"string_value", "struct_value", b"struct_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["null_value", "number_value", "string_value", "bool_value", "struct_value", "list_value", "integer_value"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___Value: _TypeAlias = Value  # noqa: Y015

@_typing.final
class ListValue(_message.Message):
    """`ListValue` is a wrapper around a repeated field of values.

    The JSON representation for `ListValue` is JSON array.
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___Value]:
        """Repeated field of dynamically typed values."""

    def __init__(
        self,
        *,
        values: _abc.Iterable[Global___Value] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListValue: _TypeAlias = ListValue  # noqa: Y015
