"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protobuf message definitions for transferring Station Control settings tree."""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from iqm.data_definitions.common.v1 import data_types_pb2 as _data_types_pb2
from iqm.data_definitions.common.v1 import parameter_pb2 as _parameter_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SingleParameterSweep(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARAMETER_NAME_FIELD_NUMBER: _builtins.int
    VALUES_FIELD_NUMBER: _builtins.int
    PARAMETER_FIELD_NUMBER: _builtins.int
    parameter_name: _builtins.str
    """Represents a sweep over several values of a single parameter.
    Values can be repeated, so that a single ParallelSweep can be used to describe an arbitrary sequence of sweep spots.
    This makes CartesianSweep somewhat redundant, but it can be more convenient to the user.
    """
    @_builtins.property
    def values(self) -> _data_types_pb2.Sequence: ...
    @_builtins.property
    def parameter(self) -> _parameter_pb2.Parameter: ...
    def __init__(
        self,
        *,
        parameter_name: _builtins.str = ...,
        values: _data_types_pb2.Sequence | None = ...,
        parameter: _parameter_pb2.Parameter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "parameter", b"parameter", "values", b"values"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_parameter", b"_parameter", "parameter", b"parameter", "parameter_name", b"parameter_name", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__parameter: _TypeAlias = _typing.Literal["parameter"]  # noqa: Y015
    _WhichOneofArgType__parameter: _TypeAlias = _typing.Literal["_parameter", b"_parameter"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parameter) -> _WhichOneofReturnType__parameter | None: ...

Global___SingleParameterSweep: _TypeAlias = SingleParameterSweep  # noqa: Y015

@_typing.final
class ParallelSweep(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SINGLE_PARAMETER_SWEEPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def single_parameter_sweeps(self) -> _containers.RepeatedCompositeFieldContainer[Global___SingleParameterSweep]:
        """The sweep spots of a ParallelSweep are the parallel pairing of the spots of the constituent SingleParameterSweeps,
        zip(x, y, ...) == [(x1, y1, ...), (x2, y2, ...), ..., (xmax, ymax, ...)]. The SingleParameterSweeps have to be equally long.
        """

    def __init__(
        self,
        *,
        single_parameter_sweeps: _abc.Iterable[Global___SingleParameterSweep] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["single_parameter_sweeps", b"single_parameter_sweeps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ParallelSweep: _TypeAlias = ParallelSweep  # noqa: Y015

@_typing.final
class CartesianSweep(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARALLEL_SWEEPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def parallel_sweeps(self) -> _containers.RepeatedCompositeFieldContainer[Global___ParallelSweep]:
        """The sweep spots of an CartesianSweep are the cartesian product of the spots of the ParallelSweeps it contains.
        parallel_sweeps == [x, ..., y, z] => spots == cartesian_product(x, ..., y, z)
        == [(x1, ..., y1, z1), ..., (x1, ..., y1, zmax), (x1, ..., y2, z1), ..., (xmax, ..., ymax, zmax)].
        In all kinds of sweeps the iteration order of the sweep spots is big-endian, i.e. the first listed parameter changes the slowest.
        No parameter may appear more than once in an CartesianSweep (because otherwise its value would not be well-defined).
        """

    def __init__(
        self,
        *,
        parallel_sweeps: _abc.Iterable[Global___ParallelSweep] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["parallel_sweeps", b"parallel_sweeps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CartesianSweep: _TypeAlias = CartesianSweep  # noqa: Y015
