[build-system]
requires = [
    "hatchling>=1,<2",
    "iqm-hatch-plugins",
]
build-backend = "hatchling.build"

[project]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
]
description = "A Python-based project for providing interface and implementations for control pulses."
name = "iqm-pulse"
readme = "build/README.md"
requires-python = ">=3.11, <3.15"
dependencies = [
    "iqm-data-definitions<3,>=2.22",
    "iqm-exa-common",
    "jinja2<4,>=3.1.6",
    "numpy<3,>=2.1",
    "python-rapidjson<2,>=1.20",
    "scipy-stubs",
    "scipy<2,>=1.13.0",
]
authors = [
    { name = "IQM Finland Oy", email = "info@iqm.tech" },
]
version = "14.0.0"

[project.license]
file = "LICENSE.txt"

[project.urls]
Documentation = "https://docs.iqm.tech/iqm-pulse/"
Homepage = "https://pypi.org/project/iqm-pulse/"

[project.optional-dependencies]
pin-iqm = [
    "iqm-exa-common==28.0.0",
]
pin-all = [
    "annotated-types==0.7.0",
    "certifi==2026.1.4",
    "charset-normalizer==3.4.4",
    "idna==3.11",
    "iqm-data-definitions==2.24",
    "iqm-exa-common==28.0.0",
    "jinja2==3.1.6",
    "markupsafe==3.0.3",
    "numpy==2.3.5",
    "optype==0.15.0",
    "packaging==24.2",
    "pandas==2.3.3",
    "protobuf==6.33.6",
    "pydantic==2.12.5",
    "pydantic-core==2.41.5",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.2",
    "python-rapidjson==1.20",
    "pytz==2024.1",
    "requests==2.32.3",
    "ruamel-yaml==0.17.32",
    "ruamel-yaml-clib==0.2.11; python_full_version < '3.12' and platform_python_implementation == 'CPython'",
    "scipy==1.17.0",
    "scipy-stubs==1.16.0.0",
    "six==1.16.0",
    "types-protobuf==6.32.1.20251210",
    "types-requests==2.32.4.20260107",
    "types-six==1.17.0.20251009",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "tzdata==2025.3",
    "urllib3==2.6.3",
    "xarray==2024.10.0",
]

[tool.hatch.build.targets.wheel]
packages = [
    "src/iqm",
]

[tool.hatch.build.targets.sdist]
exclude = [
    "tests/",
    "changelog/",
    "pytest.ini",
    "mise.toml",
    "mise/",
    "docs/",
]

[tool.mypy]
explicit_package_bases = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "daemon.*",
    "quimb.*",
    "qiskit.*",
    "qiskit_aer.*",
    "grpc.*",
    "lmfit.*",
    "emukit.*",
    "mockito.*",
    "sklearn.*",
    "dill.*",
    "uncertainties.*",
    "pythonjsonlogger.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "iqm.models.*",
]
follow_imports = "skip"
follow_imports_for_stubs = true

[tool.ruff]
exclude = [
    "*.ipynb",
    "*.rst",
]
extend-include = [
    "sub-setup-py.template",
]
line-length = 120

[tool.ruff.lint]
ignore = [
    "D107",
    "D203",
    "D213",
    "ANN002",
    "ANN003",
    "ANN204",
    "ANN401",
]
select = [
    "E4",
    "E7",
    "E9",
    "E5",
    "F",
    "Q",
    "PL",
    "I",
    "D",
    "UP007",
    "UP006",
    "UP035",
    "ANN",
    "NPY",
    "PERF401",
    "PERF402",
    "PERF403",
]
unfixable = [
    "F401",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = [
    "exa.experiments",
    "exa.core",
    "exa.common",
    "iqm.cocos",
    "iqm.gbc",
    "iqm.calibration_graphs",
    "iqm.pulse",
    "iqm.cpc",
    "iqm.pulla",
    "iqm.station_control",
    "tests",
]
known-local-folder = [
    "src",
]
known-third-party = [
    "exa",
    "iqm",
]
relative-imports-order = "closest-to-furthest"

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = [
    "F401",
]
"src/*" = [
    "PLR2004",
    "D102",
    "D105",
    "D401",
]
"tests/*" = [
    "PLR2004",
    "PLR0402",
    "D",
    "ANN001",
    "ANN201",
    "ANN202",
]

[tool.ruff.lint.pylint]
max-args = 8
max-branches = 16
max-locals = 21
max-returns = 9
max-statements = 60

[tool.coverage.paths]
source = [
    "src/",
    "*/site-packages/",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self\\.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
]

[tool.coverage.run]
branch = true
source = [
    "iqm.pulse",
]

[tool.pytest.ini_options]
nb_diff_ignore = [
    "/metadata/language_info",
    "/metadata/widgets",
    "/cells/*/execution_count",
    "/cells/*/outputs",
]
