"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Station Task definition.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from iqm.data_definitions.common.v1 import data_types_pb2 as _data_types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SweepResultsResponse(_message.Message):
    """Response body for GET /sweeps/{uuid}/results"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ResultsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _data_types_pb2.Arrays: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _data_types_pb2.Arrays | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SWEEP_ID_FIELD_NUMBER: _builtins.int
    RESULTS_FIELD_NUMBER: _builtins.int
    sweep_id: _builtins.str
    """A UUID that gives identity to the sweep event."""
    @_builtins.property
    def results(self) -> _containers.MessageMap[_builtins.str, _data_types_pb2.Arrays]:
        """Maps the names of SweepRequest.return_parameters to corresponding list of results arrays.
        The length of the list is equal to the total number of sweep spots -
        each item in the list contains the full results for one sweep spot,
        and they appear in the order dictated by sweep linearization convention.
        """

    def __init__(
        self,
        *,
        sweep_id: _builtins.str = ...,
        results: _abc.Mapping[_builtins.str, _data_types_pb2.Arrays] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results", "sweep_id", b"sweep_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SweepResultsResponse: _TypeAlias = SweepResultsResponse  # noqa: Y015

@_typing.final
class SweepResultsChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SWEEP_ID_FIELD_NUMBER: _builtins.int
    SPOT_IDX_FIELD_NUMBER: _builtins.int
    RETURN_PARAMETER_FIELD_NUMBER: _builtins.int
    ENCODED_VALUE_FIELD_NUMBER: _builtins.int
    sweep_id: _builtins.str
    """A UUID that gives identity to the sweep event."""
    spot_idx: _builtins.int
    """Zero-based sweep spot index in sweep linearization order."""
    return_parameter: _builtins.str
    """Name of the return parameter this chunk contains data for."""
    encoded_value: _builtins.bytes
    """Encoded spot-result payload for one return parameter at one sweep spot."""
    def __init__(
        self,
        *,
        sweep_id: _builtins.str = ...,
        spot_idx: _builtins.int = ...,
        return_parameter: _builtins.str = ...,
        encoded_value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoded_value", b"encoded_value", "return_parameter", b"return_parameter", "spot_idx", b"spot_idx", "sweep_id", b"sweep_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SweepResultsChunk: _TypeAlias = SweepResultsChunk  # noqa: Y015
