"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Run definition, fully defining what should be executed in the run.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from iqm.data_definitions.common.v1 import sweep_pb2 as _sweep_pb2
from iqm.data_definitions.station_control.v1 import sweep_request_pb2 as _sweep_request_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RunDefinition(_message.Message):
    """The instructions required to perform a run."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HardSweepsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _sweep_pb2.CartesianSweep: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _sweep_pb2.CartesianSweep | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    RUN_ID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    EXPERIMENT_NAME_FIELD_NUMBER: _builtins.int
    EXPERIMENT_LABEL_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    ADDITIONAL_RUN_PROPERTIES_FIELD_NUMBER: _builtins.int
    SOFTWARE_VERSION_SET_ID_FIELD_NUMBER: _builtins.int
    HARD_SWEEPS_FIELD_NUMBER: _builtins.int
    COMPONENTS_FIELD_NUMBER: _builtins.int
    DEFAULT_SWEEP_PARAMETERS_FIELD_NUMBER: _builtins.int
    DEFAULT_DATA_PARAMETERS_FIELD_NUMBER: _builtins.int
    SWEEP_DEFINITION_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Unique identifier (UUID) of the run."""
    username: _builtins.str
    """User who defined the run."""
    experiment_name: _builtins.str
    """Identifier of the experiment name."""
    experiment_label: _builtins.str
    """Freeform label of the Experiment. As opposed to `experiment_name`, no core logic relies on this value."""
    software_version_set_id: _builtins.int
    """Unique identifier of the software version set of the current Python runtime."""
    @_builtins.property
    def options(self) -> _struct_pb2.Struct:
        """Experiment-specific options or toggles that generated the run."""

    @_builtins.property
    def additional_run_properties(self) -> _struct_pb2.Struct:
        """A free-form dictionary of data, used to store information that does not fall into other categories."""

    @_builtins.property
    def hard_sweeps(self) -> _containers.MessageMap[_builtins.str, _sweep_pb2.CartesianSweep]:
        """ Maps `return_parameters` to hardware sweep specification which specifies
         how the data measured at each spot should be interpreted and shaped.
         The hard sweep specification is in the same format as `sweeps`,
         which means that the returned data can be interpreted as an N-dimensional sweep inside the spot.
         An empty list is interpreted such that the return parameter is a scalar.
         The hard sweep specification can also be `None`,
         in which case the shape will be whatever the instrument returns.
        """

    @_builtins.property
    def components(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Chip components (qubits, couplers) that are active in the run."""

    @_builtins.property
    def default_sweep_parameters(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Which of the parameters in `sweep` were added by default. The rest were added by user."""

    @_builtins.property
    def default_data_parameters(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Which of the parameters in `return_parameters` were added by default. The rest were added by user."""

    @_builtins.property
    def sweep_definition(self) -> _sweep_request_pb2.SweepRequest:
        """The instructions required to perform a sweep."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        username: _builtins.str = ...,
        experiment_name: _builtins.str = ...,
        experiment_label: _builtins.str = ...,
        options: _struct_pb2.Struct | None = ...,
        additional_run_properties: _struct_pb2.Struct | None = ...,
        software_version_set_id: _builtins.int = ...,
        hard_sweeps: _abc.Mapping[_builtins.str, _sweep_pb2.CartesianSweep] | None = ...,
        components: _abc.Iterable[_builtins.str] | None = ...,
        default_sweep_parameters: _abc.Iterable[_builtins.str] | None = ...,
        default_data_parameters: _abc.Iterable[_builtins.str] | None = ...,
        sweep_definition: _sweep_request_pb2.SweepRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["additional_run_properties", b"additional_run_properties", "options", b"options", "sweep_definition", b"sweep_definition"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["additional_run_properties", b"additional_run_properties", "components", b"components", "default_data_parameters", b"default_data_parameters", "default_sweep_parameters", b"default_sweep_parameters", "experiment_label", b"experiment_label", "experiment_name", b"experiment_name", "hard_sweeps", b"hard_sweeps", "options", b"options", "run_id", b"run_id", "software_version_set_id", b"software_version_set_id", "sweep_definition", b"sweep_definition", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RunDefinition: _TypeAlias = RunDefinition  # noqa: Y015
