"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Request to Station Control, fully defining what should be executed.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from iqm.data_definitions.common.v1 import playlist_pb2 as _playlist_pb2
from iqm.data_definitions.common.v1 import setting_pb2 as _setting_pb2
from iqm.data_definitions.common.v1 import sweep_pb2 as _sweep_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SweepRequest(_message.Message):
    """The instructions required to perform a sweep."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AwgsToPlaylistsAsJsonEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SWEEP_ID_FIELD_NUMBER: _builtins.int
    SETTINGS_FIELD_NUMBER: _builtins.int
    SWEEPS_FIELD_NUMBER: _builtins.int
    RETURN_PARAMETERS_FIELD_NUMBER: _builtins.int
    AWGS_TO_PLAYLISTS_AS_JSON_FIELD_NUMBER: _builtins.int
    DUT_LABEL_FIELD_NUMBER: _builtins.int
    PLAYLIST_FIELD_NUMBER: _builtins.int
    RUN_METADATA_FIELD_NUMBER: _builtins.int
    sweep_id: _builtins.str
    """Unique identifier (UUID) of the sweep."""
    dut_label: _builtins.str
    """Describes which DUT of the station control should be used."""
    @_builtins.property
    def settings(self) -> _setting_pb2.SettingNode:
        """Initial settings that define the state of the devices."""

    @_builtins.property
    def sweeps(self) -> _sweep_pb2.CartesianSweep:
        """Describes which parameters in settings to iterate over."""

    @_builtins.property
    def return_parameters(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Which parameters to read from the instruments and save to the database."""

    @_builtins.property
    def awgs_to_playlists_as_json(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Mapping from each AWG to the corresponding Playlist. The format is serialized as JSON, to be replaced with a proto."""

    @_builtins.property
    def playlist(self) -> _playlist_pb2.Playlist:
        """Sequence of instruction schedules to run on the instruments for each sweep spot."""

    @_builtins.property
    def run_metadata(self) -> Global___RunMetadata:
        """Obsolescent metadata about a run that Exa needs to save."""

    def __init__(
        self,
        *,
        sweep_id: _builtins.str = ...,
        settings: _setting_pb2.SettingNode | None = ...,
        sweeps: _sweep_pb2.CartesianSweep | None = ...,
        return_parameters: _abc.Iterable[_builtins.str] | None = ...,
        awgs_to_playlists_as_json: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        dut_label: _builtins.str | None = ...,
        playlist: _playlist_pb2.Playlist | None = ...,
        run_metadata: Global___RunMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_dut_label", b"_dut_label", "_run_metadata", b"_run_metadata", "dut_label", b"dut_label", "playlist", b"playlist", "run_metadata", b"run_metadata", "settings", b"settings", "sweeps", b"sweeps"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_dut_label", b"_dut_label", "_run_metadata", b"_run_metadata", "awgs_to_playlists_as_json", b"awgs_to_playlists_as_json", "dut_label", b"dut_label", "playlist", b"playlist", "return_parameters", b"return_parameters", "run_metadata", b"run_metadata", "settings", b"settings", "sweep_id", b"sweep_id", "sweeps", b"sweeps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__dut_label: _TypeAlias = _typing.Literal["dut_label"]  # noqa: Y015
    _WhichOneofArgType__dut_label: _TypeAlias = _typing.Literal["_dut_label", b"_dut_label"]  # noqa: Y015
    _WhichOneofReturnType__run_metadata: _TypeAlias = _typing.Literal["run_metadata"]  # noqa: Y015
    _WhichOneofArgType__run_metadata: _TypeAlias = _typing.Literal["_run_metadata", b"_run_metadata"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__dut_label) -> _WhichOneofReturnType__dut_label | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__run_metadata) -> _WhichOneofReturnType__run_metadata | None: ...

Global___SweepRequest: _TypeAlias = SweepRequest  # noqa: Y015

@_typing.final
class RunMetadata(_message.Message):
    """
    Metadata about a run that Exa needs to save.
    Currently passed to Station Control for saving purposes, but not used by Station Control.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HardSweepsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _sweep_pb2.CartesianSweep: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _sweep_pb2.CartesianSweep | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    RUN_ID_FIELD_NUMBER: _builtins.int
    COMPONENTS_FIELD_NUMBER: _builtins.int
    DEFAULT_SWEEP_PARAMETERS_FIELD_NUMBER: _builtins.int
    DEFAULT_DATA_PARAMETERS_FIELD_NUMBER: _builtins.int
    HARD_SWEEPS_FIELD_NUMBER: _builtins.int
    ADDITIONAL_RUN_PROPERTIES_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    """Run ID of the EXA experiment. Used to link the Sweep request ID to a run."""
    @_builtins.property
    def components(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Chip components (qubits, couplers) that are active in the request."""

    @_builtins.property
    def default_sweep_parameters(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Which of the parameters in `sweep` were added by default. The rest were added by user."""

    @_builtins.property
    def default_data_parameters(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Which of the parameters in `return_parameters` were added by default. The rest were added by user."""

    @_builtins.property
    def hard_sweeps(self) -> _containers.MessageMap[_builtins.str, _sweep_pb2.CartesianSweep]: ...
    @_builtins.property
    def additional_run_properties(self) -> _struct_pb2.Struct:
        """Other, freeform fields."""

    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
        components: _abc.Iterable[_builtins.str] | None = ...,
        default_sweep_parameters: _abc.Iterable[_builtins.str] | None = ...,
        default_data_parameters: _abc.Iterable[_builtins.str] | None = ...,
        hard_sweeps: _abc.Mapping[_builtins.str, _sweep_pb2.CartesianSweep] | None = ...,
        additional_run_properties: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["additional_run_properties", b"additional_run_properties"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["additional_run_properties", b"additional_run_properties", "components", b"components", "default_data_parameters", b"default_data_parameters", "default_sweep_parameters", b"default_sweep_parameters", "hard_sweeps", b"hard_sweeps", "run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RunMetadata: _TypeAlias = RunMetadata  # noqa: Y015
