"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Station Task definition.
"""

from collections import abc as _abc
from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from iqm.data_definitions.common.v1 import data_types_pb2 as _data_types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SweepResultsFormat:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SweepResultsFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SweepResultsFormat.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SWEEP_RESULTS_FORMAT_UNSPECIFIED: _SweepResultsFormat.ValueType  # 0
    SWEEP_RESULTS_FORMAT_LEGACY_PROTOBUF: _SweepResultsFormat.ValueType  # 1
    SWEEP_RESULTS_FORMAT_STREAMING_V2: _SweepResultsFormat.ValueType  # 2

class SweepResultsFormat(_SweepResultsFormat, metaclass=_SweepResultsFormatEnumTypeWrapper): ...

SWEEP_RESULTS_FORMAT_UNSPECIFIED: SweepResultsFormat.ValueType  # 0
SWEEP_RESULTS_FORMAT_LEGACY_PROTOBUF: SweepResultsFormat.ValueType  # 1
SWEEP_RESULTS_FORMAT_STREAMING_V2: SweepResultsFormat.ValueType  # 2
Global___SweepResultsFormat: _TypeAlias = SweepResultsFormat  # noqa: Y015

@_typing.final
class SweepTaskRequest(_message.Message):
    """
    A task to the queue of Station Control service. Contains data related to the queuing, and the sweep request as a
    payload.
    """

    DESCRIPTOR: _descriptor.Descriptor

    QUEUE_NAME_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    SWEEP_ID_FIELD_NUMBER: _builtins.int
    SWEEP_RESULTS_FORMAT_FIELD_NUMBER: _builtins.int
    queue_name: _builtins.str
    """Name of the destination queue."""
    sweep_id: _builtins.str
    """Identifier of the sweep. Should be same as the ID contained in `payload`, but we include it here separately so
    that the payload does not have to be deserialized to see the ID.
    """
    sweep_results_format: Global___SweepResultsFormat.ValueType
    """Requested representation for the sweep_results artifact returned by Core API."""
    @_builtins.property
    def payload(self) -> _any_pb2.Any:
        """The sweep_request as serialized bitstring. We want to keep it encoded such that it does not need to be unpacked
        while the data related to queuing is processed.
        """

    def __init__(
        self,
        *,
        queue_name: _builtins.str = ...,
        payload: _any_pb2.Any | None = ...,
        sweep_id: _builtins.str = ...,
        sweep_results_format: Global___SweepResultsFormat.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "queue_name", b"queue_name", "sweep_id", b"sweep_id", "sweep_results_format", b"sweep_results_format"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SweepTaskRequest: _TypeAlias = SweepTaskRequest  # noqa: Y015

@_typing.final
class SweepResultsResponse(_message.Message):
    """Response body for GET /sweeps/{uuid}/results"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ResultsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _data_types_pb2.Array: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _data_types_pb2.Array | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SWEEP_ID_FIELD_NUMBER: _builtins.int
    RESULTS_FIELD_NUMBER: _builtins.int
    sweep_id: _builtins.str
    """A UUID that gives identity to the sweep event."""
    @_builtins.property
    def results(self) -> _containers.MessageMap[_builtins.str, _data_types_pb2.Array]:
        """Maps the names of SweepRequest.return_parameters to corresponding results arrays.
        The array shape is [s_1, s_2, ..., s_m, r], where `s_k` is the number of sweep
        spots in the k:th ParallelSweep, and `r` is the result_length of the corresponding return_parameter for one spot.
        All Arrays in `results` have the same shape except for `r`.
        """

    def __init__(
        self,
        *,
        sweep_id: _builtins.str = ...,
        results: _abc.Mapping[_builtins.str, _data_types_pb2.Array] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results", "sweep_id", b"sweep_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SweepResultsResponse: _TypeAlias = SweepResultsResponse  # noqa: Y015
