# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iqm/data_definitions/station_control/v1/task_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from iqm.data_definitions.common.v1 import data_types_pb2 as iqm_dot_data__definitions_dot_common_dot_v1_dot_data__types__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:iqm/data_definitions/station_control/v1/task_service.proto\x12\'iqm.data_definitions.station_control.v1\x1a/iqm/data_definitions/common/v1/data_types.proto\x1a\x19google/protobuf/any.proto\"\xba\x01\n\x10SweepTaskRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x10\n\x08sweep_id\x18\x03 \x01(\t\x12Y\n\x14sweep_results_format\x18\x04 \x01(\x0e\x32;.iqm.data_definitions.station_control.v1.SweepResultsFormat\"\xdc\x01\n\x14SweepResultsResponse\x12\x10\n\x08sweep_id\x18\x01 \x01(\t\x12[\n\x07results\x18\x02 \x03(\x0b\x32J.iqm.data_definitions.station_control.v1.SweepResultsResponse.ResultsEntry\x1aU\n\x0cResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.iqm.data_definitions.common.v1.Array:\x02\x38\x01*\x8b\x01\n\x12SweepResultsFormat\x12$\n SWEEP_RESULTS_FORMAT_UNSPECIFIED\x10\x00\x12(\n$SWEEP_RESULTS_FORMAT_LEGACY_PROTOBUF\x10\x01\x12%\n!SWEEP_RESULTS_FORMAT_STREAMING_V2\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iqm.data_definitions.station_control.v1.task_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SWEEPRESULTSRESPONSE_RESULTSENTRY._options = None
  _SWEEPRESULTSRESPONSE_RESULTSENTRY._serialized_options = b'8\001'
  _SWEEPRESULTSFORMAT._serialized_start=592
  _SWEEPRESULTSFORMAT._serialized_end=731
  _SWEEPTASKREQUEST._serialized_start=180
  _SWEEPTASKREQUEST._serialized_end=366
  _SWEEPRESULTSRESPONSE._serialized_start=369
  _SWEEPRESULTSRESPONSE._serialized_end=589
  _SWEEPRESULTSRESPONSE_RESULTSENTRY._serialized_start=504
  _SWEEPRESULTSRESPONSE_RESULTSENTRY._serialized_end=589
# @@protoc_insertion_point(module_scope)
