name: Test version compatibility

on:
  pull_request:
    paths:
      - 'sdk.txt'

jobs:
  mirror-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install -r sdk.txt
